[package]
name = "pchan"
version = "0.1.0"
edition = "2024"

[dependencies]
pchan-macros = { workspace = true }
pchan-utils = { workspace = true }
pchan-emu = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
const-hex = { workspace = true, features = ["alloc"] }

[workspace]
resolver = "3"
members = [
  "pchan-emu",
  "pchan-macros",
  "pchan-utils",
  "pchan-cranelift-frontend",
  "pchan-debug-tui",
]

[patch.crates-io]
cranelift-frontend = { path = "./pchan-cranelift-frontend" }

[workspace.dependencies]
const-hex = { version = "1.16.0", features = ["nightly", "portable-simd"] }
pchan-macros = { path = "./pchan-macros"}
pchan-utils = { path = "./pchan-utils"}
pchan-emu = { path = "./pchan-emu" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
color-eyre = "0.6.5"
slab = "0.4.11"

[profile.bench]
debug = true

[profile.release]
panic = "unwind"
lto = "fat"

[profile.dev]
panic = "unwind"


